name: "Playwright e2e Test"
description: "Runs playwright"

inputs:
  baseUrl:
    description: "Playwright will run test against this URL"
    required: true
  playwrightReportPath:
    description: "Playwright report output path"
    required: true
    default: "./playwright-report"
  installPlaywrightCommand:
    description: "npx playwright install <flags-and-options>"
    required: true
    default: "npx playwright install chromium --with-deps"
  installDependenciesCommand:
    description: "npm ci | yarn install --frozen-lockfile | pnpm i --frozen-lockfile"
    required: true
    default: "yarn install --frozen-lockfile"
  testPlaywrightCommand:
    description: "npx playwright test <flags-and-options>"
    required: true
    default: "npx playwright test"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: ${{ inputs.installDependenciesCommand }}
      shell: bash
    - name: Install Playwright Browsers
      run: ${{ inputs.installPlaywrightCommand }}
      shell: bash
    - name: Run Playwright tests
      run: PLAYWRIGHT_BASE_URL=${{ inputs.baseUrl }} ${{ inputs.testPlaywrightCommand }}
      shell: bash
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ${{ inputs.playwrightReportPath }}
        retention-days: 30
